# -*- coding: utf-8 -*-
"""Email Scrapper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1BLZecK4xOpBH8khYpXJvGkyTjgOX9w
"""

import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import time
from urllib.parse import urljoin, urlparse
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ---------------------------------
# 1. Create Session with Retry
# ---------------------------------
def create_session():
    session = requests.Session()

    retry_strategy = Retry(
        total=3,
        backoff_factor=1,
        status_forcelist=[429, 500, 502, 503, 504]
    )

    adapter = HTTPAdapter(max_retries=retry_strategy)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    session.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    })

    return session


# ---------------------------------
# 2. Extract Emails Using Regex
# ---------------------------------
def extract_emails(text):
    email_pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
    return re.findall(email_pattern, text)


# ---------------------------------
# 3. Get Internal Links Only
# ---------------------------------
def get_internal_links(soup, base_url):
    links = set()
    domain = urlparse(base_url).netloc

    for tag in soup.find_all("a", href=True):
        href = urljoin(base_url, tag["href"])
        parsed_href = urlparse(href)

        if parsed_href.netloc == domain:
            links.add(href)

    return links


# ---------------------------------
# 4. Crawl Website for Emails
# ---------------------------------
def crawl_for_emails(start_url, max_pages=10):
    session = create_session()
    visited = set()
    to_visit = {start_url}
    found_emails = set()

    while to_visit and len(visited) < max_pages:
        url = to_visit.pop()
        visited.add(url)

        try:
            print(f"Scraping: {url}")
            response = session.get(url, timeout=10)
            response.raise_for_status()

            soup = BeautifulSoup(response.text, "lxml")

            # Extract emails from raw HTML
            emails = extract_emails(response.text)
            found_emails.update(emails)

            # Get internal links for crawling
            internal_links = get_internal_links(soup, start_url)

            for link in internal_links:
                if link not in visited:
                    to_visit.add(link)

            time.sleep(2)  # polite delay

        except requests.exceptions.RequestException:
            continue

    return found_emails


# ---------------------------------
# 5. Run Scraper
# ---------------------------------
if __name__ == "__main__":
    website_url = "https://www.linkedin.com/"  # Replace with target site

    emails = crawl_for_emails(website_url, max_pages=20)

    print("\nEmails Found:")
    for email in emails:
        print(email)

    # Save to CSV
    df = pd.DataFrame(list(emails), columns=["Email"])
    df.to_csv("scraped_emails.csv", index=False)

    print(f"\nTotal Emails Found: {len(emails)}")

data = pd.read_csv("/content/scraped_emails.csv")

data

